[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12.0

[colors.primary]
background = "0x1e1e2f"
foreground = "0xc5c8c6"

[colors.normal]
black = "0x1c1c1c"
red = "0xc82829"
green = "0xb9ca4a"
yellow = "0xeab700"
blue = "0x7aa6da"
magenta = "0xb77ee0"
cyan = "0x70c3c9"
white = "0xeeeeee"

[colors.bright]
black = "0x666666"
red = "0xf92672"
green = "0xa6e22e"
yellow = "0xe6db74"
blue = "0x66d9ef"
magenta = "0x9e6ffe"
cyan = "0xa1efe4"
white = "0xffffff"

[keyboard]
bindings = [
	{ key = "V", mods = "Control|Shift", action = "Paste" },
	{ key = "C", mods = "Control|Shift", action = "Copy" },
	{ key = "Q", mods = "Control|Shift", action = "Quit" },
]

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"

[cursor]
style.shape = "Beam"
style.blinking = "On"
