[general]
# import = ["~/.config/alacritty/themes/themes/dracula_plus.toml"]
# import = ["~/.config/alacritty/themes/themes/gnome_terminal.toml"]
# import = ["~/.config/alacritty/themes/themes/horizon_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/linux.toml"]
# import = ["~/.config/alacritty/themes/themes/material_theme_mod.toml"]
# import = ["~/.config/alacritty/themes/themes/monokai.toml"]
# import = ["~/.config/alacritty/themes/themes/monokai_charcoal.toml"]
# import = ["~/.config/alacritty/themes/themes/monokai_pro.toml"]
# import = ["~/.config/alacritty/themes/themes/papercolor_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/papercolor_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/pencil_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/pencil_light.toml"]
# import = ["~/.config/alacritty/themes/themes/smoooooth.toml"]
# import = ["~/.config/alacritty/themes/themes/vscode.toml"]
[env]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "full"
# opacity = 0.9
opacity = 1
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors]
cursor = { text = "#c5c8c6", cursor = "#7c7c7c" }
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#ffffff", background = "#ac4242" }

[cursor]
style.shape = "Beam"
style.blinking = "On"
thickness = 0.2

[keyboard]
bindings = [
	{ key = "V", mods = "Control|Shift", action = "Paste" },
	{ key = "C", mods = "Control|Shift", action = "Copy" },
	{ key = "Q", mods = "Control|Shift", action = "Quit" },
	{ key = "Enter", mods = "Control|Shift", action = "ToggleFullscreen" },
	{ key = "K", mods = "Control|Shift", action = "ClearHistory" },
	{ key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
	{ key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
	{ key = "Home", mods = "Shift", action = "ScrollToTop" },
	{ key = "End", mods = "Shift", action = "ScrollToBottom" },
	{ key = "Up", mods = "Control", action = "ScrollLineUp" },
	{ key = "Down", mods = "Control", action = "ScrollLineDown" },
	{ key = "+", mods = "Control", action = "IncreaseFontSize" },
	{ key = "-", mods = "Control", action = "DecreaseFontSize" },
	{ key = "\\", mods = "Control", action = "ResetFontSize" },
	{ key = "T", mods = "Control|Shift", action = "SpawnNewInstance" },
	{ key = "N", mods = "Control|Shift", action = "SearchHistoryNext" },
	{ key = "P", mods = "Control|Shift", action = "SearchHistoryPrevious" },
	{ key = "Enter", mods = "None", mode = "Search", action = "SearchConfirm" },
	{ key = "Tab", mods = "None", mode = "Search", action = "SearchFocusNext" },
	{ key = "Tab", mods = "Shift", mode = "Search", action = "SearchFocusPrevious" },
	{ key = "Escape", mods = "None", mode = "Search", action = "SearchCancel" },
	{ key = "C", mods = "Control", mode = "Search", action = "SearchClear" },
]
